maxSeq: test-subseq.o maxSeq.o
	gcc -pedantic -std=gnu99 -Wall -Werror test-subseq.o maxSeq.o -o maxSeq
test-subseq.o: test-subseq.c
	gcc -std=gnu99 -Wall -Werror -c test-subseq.c
maxSeq.o: maxSeq.c
	gcc -pedantic -std=gnu99 -Wall -Werror -c maxSeq.c
